/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import entidades.Categoria;
import javax.swing.JOptionPane;
import persistencia.CategoriaDAO;

/**
 *
 * @author suporte
 */
public class TelaCadastroCategoria extends javax.swing.JFrame {
    
    private Categoria categoria = new Categoria();
    private TelaListaCategoria telaListagem;

    /**
     * Creates new form TelaCadastroCategoria
     */
    public TelaCadastroCategoria(TelaListaCategoria telaListagem) {
        initComponents();
        this.telaListagem = telaListagem;
    }

    TelaCadastroCategoria() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void setCategoria( Categoria categoria) {
        this.categoria = categoria;
        txtCategoria.setText(categoria.getNome());
        if (categoria.getTipo() == 'F') {
            rdbFilme.setSelected(true);
    } else if (categoria.getTipo() == 'J') {
            rdbJogo.setSelected(true);
        }
    }    
 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdbFilme = new javax.swing.JRadioButton();
        rdbJogo = new javax.swing.JRadioButton();
        txtCategoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Categoria");

        grpTipo.add(rdbFilme);
        rdbFilme.setText("Filme");
        rdbFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFilmeActionPerformed(evt);
            }
        });

        grpTipo.add(rdbJogo);
        rdbJogo.setText("Jogo");

        jLabel2.setText("Tipo");

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbJogo))
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnGravar))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbFilme)
                    .addComponent(rdbJogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGravar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFilmeActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        categoria.setNome(txtCategoria.getText());
        if (rdbFilme.isSelected()) {
            categoria.setTipo('F');
        } else if (rdbJogo.isSelected()) {
            categoria.setTipo('J');
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o tipo de categoria.");
        }
        
        if (categoria.getTipo() != ' ') {
            if (categoria.getId() == 0) {
                inserir();
            } else {
                alterar();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Selecione o tipo de categoria");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void inserir() {
          if (CategoriaDAO.inserir(categoria)) {
                JOptionPane.showMessageDialog(this, "Categoria inserida com sucesso!");
                telaListagem.montarListaCategorias();
                dispose(); //Fechar a tela de cadastro
            } else {
                JOptionPane.showConfirmDialog(this, "Erro ao inserir categoria");
            }
    }
    
    private void alterar() {
                  if (CategoriaDAO.alterar(categoria)) {
                JOptionPane.showMessageDialog(this, "Categoria alterada com sucesso!");
                telaListagem.montarListaCategorias();
                dispose(); //Fechar a tela de cadastro
            } else {
                JOptionPane.showConfirmDialog(this, "Erro ao alterar a categoria");
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.ButtonGroup grpTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdbFilme;
    private javax.swing.JRadioButton rdbJogo;
    private javax.swing.JTextField txtCategoria;
    // End of variables declaration//GEN-END:variables
}
